// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQZgSonMz7zZQrMo9nTC_LoKScHj13ksE',
    appId: '1:803220231093:web:723a50c061ccb330c47ffc',
    messagingSenderId: '803220231093',
    projectId: 'reviewrestopab2',
    authDomain: 'reviewrestopab2.firebaseapp.com',
    storageBucket: 'reviewrestopab2.firebasestorage.app',
    measurementId: 'G-0TCJHJBM67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjEhfqwvrEiQvPVQSHytChk3CQ096LJGA',
    appId: '1:803220231093:android:2ade7c3db5f3c7f3c47ffc',
    messagingSenderId: '803220231093',
    projectId: 'reviewrestopab2',
    storageBucket: 'reviewrestopab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaqBveuhlCA9zNSFKF2-Ts5U3eXLhJA2k',
    appId: '1:803220231093:ios:f05a2b7511b56ba0c47ffc',
    messagingSenderId: '803220231093',
    projectId: 'reviewrestopab2',
    storageBucket: 'reviewrestopab2.firebasestorage.app',
    iosBundleId: 'com.example.reviewrestopab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaqBveuhlCA9zNSFKF2-Ts5U3eXLhJA2k',
    appId: '1:803220231093:ios:f05a2b7511b56ba0c47ffc',
    messagingSenderId: '803220231093',
    projectId: 'reviewrestopab2',
    storageBucket: 'reviewrestopab2.firebasestorage.app',
    iosBundleId: 'com.example.reviewrestopab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQZgSonMz7zZQrMo9nTC_LoKScHj13ksE',
    appId: '1:803220231093:web:f8c1758a5c68b3b5c47ffc',
    messagingSenderId: '803220231093',
    projectId: 'reviewrestopab2',
    authDomain: 'reviewrestopab2.firebaseapp.com',
    storageBucket: 'reviewrestopab2.firebasestorage.app',
    measurementId: 'G-0GPTM1NFCT',
  );

}